CREATE TABLE users (
	id INT NOT NULL PRIMARY KEY IDENTITY,
	name VARCHAR(100) NOT NULL,
	hash TEXT NOT NULL,
	salt VARCHAR(255) NOT NULL,
	iterations INT NOT NULL,
	accType INT NOT NULL,
	birth DATE NOT NULL
)